version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"

  # PostgreSQL service
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: petfinder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
